### ISSUE TITLE
[FE] 스토리북 배포 워크플로우 캐시 경로 수정

### ISSUE THREAD

**Issue by HyeryongChoi** [woowacourse-teams/2023-zipgo#467]
### 🐞 Describe

Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
위와 같은 경고가 떠서 캐시 경로를 수정하려고 합니다!

```yaml
     - name: Cache Yarn global cache
        uses: actions/cache@v3
        with:
          path: '**/.yarn'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Yarn project cache
        uses: actions/cache@v3
        with:
          path: '**/.yarn/cache'
          key: ${{ runner.os }}-yarn-project-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-project-
```

### 📄 Logs

```shell
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

### 🕖 예상 작업 소요 시간

10분

### 🌏 Environment

.
